version: "3.7"

services:

  msprodutos:
    container_name: msprodutos
    build:
      context: /msproduto
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbproduto:3306/produtos?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - dbproduto
    networks:
      - minha-rede

  dbproduto:
    container_name: dbproduto
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: produtos
    volumes:
      - db_produto:/var/lib/mysql
    networks:
      - minha-rede

  dbpedido:
    container_name: dbpedido
    image: mysql:5.7
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pedidos
    volumes:
      - db_pedido:/var/lib/mysql
    networks:
      - minha-rede

  mspedidos:
    container_name: mspedidos
    build:
      context: /mspedido
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbpedido:3306/pedidos?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - dbpedido
    networks:
      - minha-rede

  mslogistica:
    container_name: mslogistica
    build:
      context: /mslogistica
      dockerfile: Dockerfile
    ports:
      - '8084:8084'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dblogistica:3306/logistica?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456  
    depends_on:
      - mspedidos
      - dblogistica
    volumes:
      - mslogistica:/app/relatorios/
    networks:
      - minha-rede

  msclientes:
    container_name: msclientes
    build:
      context: /mscliente
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbcliente:3306/clientes?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - dbcliente
    networks:
      - minha-rede

  dbcliente:
    container_name: dbcliente
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clientes
    volumes:
      - db_client:/var/lib/mysql
    networks:
      - minha-rede

  msbatch:
    container_name: msbatch
    build:
      context: /msbatch
      dockerfile: Dockerfile
    ports:
      - '8089:8089'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbproduto:3306/produtos?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - dbproduto
      - msprodutos
      - dbcliente
      - msclientes
      - dbpedido
      - mspedidos
    networks:
      - minha-rede

  dblogistica:
    container_name: dblogistica
    image: mysql:5.7
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: logistica
    volumes:
      - db_logistica:/var/lib/mysql
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

volumes:
  db_client:
  db_produto:
  db_pedido:
  db_logistica:
  mslogistica: