server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:clientes
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true